version: '3.8'

services:
  backend:
    build: 
      context: ./mern/backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    networks:
      - app-network

  frontend:
    build: 
      context: ./mern/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - BACKEND_URL=http://13.219.75.233:3001

    networks:
      - app-network

networks:
  app-network:
    driver: bridge