version: '3'
services:
  backend:
    build: ./mern/backend
    container_name: backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - SERVICE_NAME=backend

  frontend:
    build: ./mern/frontend
    container_name: frontend
    ports:
      - "80:3000"
    depends_on:
      - backend
    environment:
      - PORT=3000
      - SERVICE_NAME=frontend
      - BACKEND_URL=http://13.219.75.233:3001/hostname
